# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92dcb23a84809bc03f6be6adf5263f92"
name = "customer-card-change"
handle = "customer-card-change"
application_url = "https://customer-card.onrender.com/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers"

[auth]
redirect_urls = [
  "https://customer-card.onrender.com//auth/callback",
  "https://customer-card.onrender.com//auth/shopify/callback",
  "https://customer-card.onrender.com//api/auth/callback"
]

[pos]
embedded = false
